# Generated by Django 5.0.5 on 2024-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_tree_description_alter_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='common_name',
            field=models.CharField(default='common', max_length=200),
        ),
    ]
