# Generated by Django 5.0.5 on 2024-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='img_url',
            field=models.CharField(default='image', max_length=999),
        ),
    ]
