# Generated by Django 5.0.5 on 2024-06-06 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_alter_plantorder_site_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantorder',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.site'),
        ),
        migrations.AlterField(
            model_name='plantorder',
            name='tree_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.tree'),
        ),
        migrations.AlterField(
            model_name='plantorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
