# Generated by Django 5.0.4 on 2024-06-06 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_alter_plantorder_site_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantorder',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.site', to_field='name'),
        ),
        migrations.AlterField(
            model_name='plantorder',
            name='tree_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.tree', to_field='name'),
        ),
        migrations.AlterField(
            model_name='plantorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
